name: Deploy MeiliSearch to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        id: apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="key_name=${{ secrets.AWS_KEY_NAME }}"
      
      - name: Get Public IP
        id: public_ip
        run: |
          PUBLIC_IP=$(terraform -chdir=terraform output -raw meilisearch_public_ip)
          echo "ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
          echo "Public IP is: $PUBLIC_IP"

      - name: Wait for EC2 to be ready
        run: |
          echo "Waiting 60 seconds for EC2 instance to fully boot..."
          sleep 60

      - name: Setup MeiliSearch on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ steps.public_ip.outputs.ip }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          timeout: 300s
          script: |
            sudo yum update -y
            sudo amazon-linux-extras install docker -y
            sudo service docker start
            sudo usermod -a -G docker ec2-user
            
            if [ ! -e /dev/sdh ]; then
              echo "Device /dev/sdh does not exist"
            elif ! sudo file -s /dev/sdh | grep -q "filesystem"; then
              sudo mkfs -t ext4 /dev/sdh
            fi
            
            sudo mkdir -p /data
            sudo mount /dev/sdh /data || true
            echo "/dev/sdh /data ext4 defaults,nofail 0 2" | sudo tee -a /etc/fstab
            
            sudo mkdir -p /data/meili_data
            
            docker run -d --restart always \
              -p 7700:7700 \
              -v /data/meili_data:/meili_data \
              --env MEILI_MASTER_KEY='${{ secrets.MEILI_MASTER_KEY }}' \
              getmeili/meilisearch:latest 